#pragma once

#define DATA_MEMORY_SIZE 4096

#define PHYS_REGS_COUNT 60
#define ARCH_REGS_COUNT 32
#define CC_REGS_COUNT   10

#define FREE_LIST_CAPACITY 60

#define IRS_CAPACITY 8
#define MRS_CAPACITY 2
#define LSQ_CAPACITY 6

#define INT_FU_STAGES 1
#define MUL_FU_STAGES 4
#define MEM_FU_STAGES 3

#define ROB_CAPACITY 80

#define BIS_CAPACITY 60